export const metadata = {
  title: 'Next',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <h1>shop</h1>
      <div>{children}</div>
    </>
  )
}
